// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGPSExif(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetGPSExif(arg1:string,arg2:number,arg3:number):Promise<void>;
