// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGPSExif(arg1:main.GetExifParams):Promise<main.GetExifResponse>;

export function Greet(arg1:string):Promise<string>;

export function SetGPSExif(arg1:main.SetExifParams):Promise<main.SetExifResponse>;
