// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGPSExif(arg1) {
  return window['go']['main']['App']['GetGPSExif'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetGPSExif(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGPSExif'](arg1, arg2, arg3);
}
